python3 crawler.py image/bunkei/backpack バックパック
python3 crawler.py image/bunkei/banana バナナ
python3 crawler.py image/bunkei/baseball_bat 野球バット
python3 crawler.py image/bunkei/baseball_glove 野球グローブ
python3 crawler.py image/bunkei/bed ベッド
python3 crawler.py image/bunkei/bench ベンチ
python3 crawler.py image/bunkei/bird 鳥
python3 crawler.py image/bunkei/book 本
python3 crawler.py image/bunkei/bottle ボトル
python3 crawler.py image/bunkei/cake ケーキ
python3 crawler.py image/bunkei/carrot 人参
python3 crawler.py image/bunkei/cat 猫
python3 crawler.py image/bunkei/chair 椅子
python3 crawler.py image/bunkei/couch ソファ
python3 crawler.py image/bunkei/cow 牛
python3 crawler.py image/bunkei/cup コップ
python3 crawler.py image/bunkei/dining_table ダイニングテーブル
python3 crawler.py image/bunkei/dog 犬
python3 crawler.py image/bunkei/frisbee フリスビー
python3 crawler.py image/bunkei/giraffe キリン
python3 crawler.py image/bunkei/handbag ハンドバッグ
python3 crawler.py image/bunkei/horse 馬
python3 crawler.py image/bunkei/hot_dog ホットドッグ
python3 crawler.py image/bunkei/orange オレンジ
python3 crawler.py image/bunkei/person 人
python3 crawler.py image/bunkei/potted_plant 植木鉢
python3 crawler.py image/bunkei/sandwich サンドイッチ
python3 crawler.py image/bunkei/sheep 羊
python3 crawler.py image/bunkei/sink シンク
python3 crawler.py image/bunkei/skateboard スケートボード
python3 crawler.py image/bunkei/skis スキー
python3 crawler.py image/bunkei/snowboard スノーボード
python3 crawler.py image/bunkei/sports_ball ボール
python3 crawler.py image/bunkei/stop_sign 標識
python3 crawler.py image/bunkei/suitcase スーツケース
python3 crawler.py image/bunkei/surfboard サーフボード
python3 crawler.py image/bunkei/teddy_bear テディベア
python3 crawler.py image/bunkei/tennis_racket テニスラケット
python3 crawler.py image/bunkei/tie ネクタイ
python3 crawler.py image/bunkei/toaster トースター
python3 crawler.py image/bunkei/vase 花瓶
python3 crawler.py image/bunkei/wine_glass ワイングラス
python3 crawler.py image/rikei/airplane 飛行機
python3 crawler.py image/rikei/apple 林檎
python3 crawler.py image/rikei/bear 熊
python3 crawler.py image/rikei/bicycle 自転車
python3 crawler.py image/rikei/boat ボート
python3 crawler.py image/rikei/bowl ボウル
python3 crawler.py image/rikei/broccoli ブロッコリー
python3 crawler.py image/rikei/bus バス
python3 crawler.py image/rikei/car 車
python3 crawler.py image/rikei/cell_phone 携帯電話
python3 crawler.py image/rikei/clock 時計
python3 crawler.py image/rikei/donut ドーナツ
python3 crawler.py image/rikei/elephant 象
python3 crawler.py image/rikei/fire_hydrant 消火栓
python3 crawler.py image/rikei/fork フォーク
python3 crawler.py image/rikei/hair_drier ドライヤー
python3 crawler.py image/rikei/keyboard PCキーボード
python3 crawler.py image/rikei/kite 凧
python3 crawler.py image/rikei/knife ナイフ
python3 crawler.py image/rikei/laptop ノートパソコン
python3 crawler.py image/rikei/microwave 電子レンジ
python3 crawler.py image/rikei/motorcycle バイク
python3 crawler.py image/rikei/mouse PCマウス
python3 crawler.py image/rikei/oven オーブントースター
python3 crawler.py image/rikei/parking_meter パーキングメーター
python3 crawler.py image/rikei/pizza ピザ
python3 crawler.py image/rikei/refrigerator 冷蔵庫
python3 crawler.py image/rikei/remote リモコン
python3 crawler.py image/rikei/scissors ハサミ
python3 crawler.py image/rikei/spoon スプーン
python3 crawler.py image/rikei/toilet トイレ
python3 crawler.py image/rikei/toothbrush 歯ブラシ
python3 crawler.py image/rikei/traffic_light 信号機
python3 crawler.py image/rikei/train 電車
python3 crawler.py image/rikei/truck トラック
python3 crawler.py image/rikei/tv テレビ
python3 crawler.py image/rikei/umbrella 傘
python3 crawler.py image/rikei/zebra シマウマ
