python3 crawler.py image/bunkei/baseball_bat 野球バット
python3 crawler.py image/bunkei/chair 椅子
python3 crawler.py image/bunkei/frisbee フリスビー
python3 crawler.py image/bunkei/hot_dog ホットドッグ
python3 crawler.py image/bunkei/potted_plant 植木鉢
python3 crawler.py image/bunkei/stop_sign 標識
python3 crawler.py image/rikei/bicycle 自転車
python3 crawler.py image/rikei/bus バス
python3 crawler.py image/rikei/hair_drier ドライヤー
python3 crawler.py image/rikei/parking_meter パーキングメーター
python3 crawler.py image/rikei/refrigerator 冷蔵庫
python3 crawler.py image/rikei/toothbrush 歯ブラシ
python3 crawler.py image/rikei/train 電車
